In [2]:
# 混同行列

In [5]:
from sklearn.metrics import confusion_matrix
import numpy as np

In [4]:
y_true = [1,0,1,1,0,1,1,0]
y_pred = [0,0,1,1,0,0,1,1]

In [13]:
(np.array(y_true) ==1) & (np.array(y_pred) == 1)

array([False, False,  True,  True, False, False,  True, False])

In [20]:
tp = np.sum((np.array(y_true) == 1) & (np.array(y_pred) == 1))
tn = np.sum((np.array(y_true) == 0) & (np.array(y_pred) == 0))

fp = np.sum((np.array(y_true) == 0) & (np.array(y_pred) == 1))
fn = np.sum((np.array(y_true) == 1) & (np.array(y_pred) == 0))

In [21]:
np.array([
    [tp,fp],
    [fn,tn]
])

array([[3, 1],
       [2, 2]])

In [18]:
confusion_matrix(y_true,y_pred)

array([[2, 1],
       [2, 3]])